peteflo-i7gtx:
  peteflo:
    path_to_data_directory: '/media/peteflo/3TBbackup/dense_correspondence'

paladin-23:
  manuelli:
    path_to_data_directory: '/home/manuelli/data'

paladin-44:
  manuelli:
    path_to_data_directory: '/media/hdd/data'

iiwa-2:
  manuelli:
    path_to_data_directory: '/home/manuelli/data'

wei:
  wei:
    path_to_data_directory: '/home/wei/data'

jakub-ThinkPad-T480:
  jakub:
    path_to_data_directory: '/home/jakub/data'
