logs_root_path: logs_proto
object_id: "shoe_gray_nike"
train:
- "2018-05-15-00-29-54-overfit-small-dataset"
test:
- "2018-05-15-00-29-54-overfit-small-dataset"
evaluation_labeled_data_path:
- "evaluation_labeled_data/shoe_gray_nike.yaml"
